# Makefile for MS3DVAR Filter variant
#
# This is a simple variant-specific Makefile that includes
# the common build rules from ../Makefile.inc

# Variant-specific settings
VARIANT_NAME = FILTER
SBIN = msfilter

# Include common build rules
include ../Makefile.inc
