#!/bin/bash
#OAR --project airsea-modeling
#OAR -l /nodes=1/cpu=1/core=1,walltime=48:00:00
################################################################################
case $1 in
  --env-ok)
    shift;;
  --fast)
    shift
    pwd=`pwd`
    . $pwd/.croco-guix-profile/etc/profile && $0 --env-ok $@
    ;;
  *)
    set -x
    MYDIR=`dirname $0`
    # guix environment setup
    # export PATH=/var/guix/profiles/per-user/root/current-guix/bin:$PATH
    # export GUIX_DAEMON_SOCKET=guix://luke.u-ga.fr
    [ -f /applis/site/guix-start.sh ] && . /applis/site/guix-start.sh
    #export PATH="$HOME/.guix-profile/bin${PATH:+:}$PATH"
    #export PATH="$HOME/.config/guix/current/bin:${PATH}"
    pwd=`pwd`
    rm -f $pwd/.croco-guix-profile
    packages="gcc-toolchain gfortran-toolchain make \
        netcdf netcdf-fortran \
        mpich openssh \
        openblas lapack \
        openjdk coreutils binutils sed grep bash which time patch gdb"
    guix_cmd="guix time-machine --commit=fa59a22140bcb98fa6e5cf895deaa5f2fbdb9bcf --"
    exec $guix_cmd environment -m $MYDIR/adjoinable-mpi.scm --root=$pwd/.croco-guix-profile --preserve='OAR*' --pure --ad-hoc $packages -- $0 --env-ok $@
    ;;
esac
################################################################################

set -x
set -e

case $1 in
  --exec)
    echo $@
    shift; exec $@;;
esac

if [ -f "$OAR_NODE_FILE" ]; then
  nbcores=`cat $OAR_NODE_FILE|wc -l`
  mpirun_cmd="mpirun -n $nbcores -launcher ssh -launcher-exec /usr/bin/oarsh --machinefile $OAR_NODE_FILE"
else
  nbcores=16
  mpirun_cmd="mpirun -n $nbcores"
fi

if [ -f AD/tapenade_3.16/bin/tapenade ]; then
    echo found tapenade in `pwd`/AD/tapenade_3.16/bin/tapenade
    export TAPENADE=`pwd`/AD/tapenade_3.16/bin/tapenade
fi

mkdir -p RunBC
cd RunBC

# 1. first run: build of obs.dat
cp -f ../AD/croco.basin-obs.in .

cp -f ../OCEAN/cppdefs.h .
sed -i 's/define[\t ]*REGIONAL/undef REGIONAL/' cppdefs.h
#sed -i 's/define[\t ]*SOLVE3D/undef SOLVE3D/' cppdefs.h
sed -i 's/undef[\t ]*BASIN/define BASIN/' cppdefs.h
sed -i 's/undef[\t ]*TAPENADE/define TAPENADE/' cppdefs.h
#sed -i 's/undef[\t ]*BATHY_MAY_BE_MODIFIED/define BATHY_MAY_BE_MODIFIED/' cppdefs.h
sed -i 's/undef[\t ]*PENALIZATION/define PENALIZATION/' cppdefs.h
sed -i 's/undef[\t ]*MPI/define MPI/' cppdefs.h
#sed -i 's/undef[\t ]*TAPENADE/define TAPENADE\n# define AUTOTILING/' cppdefs.h
../OCEAN/jobcomp
cd Compile
make croco && mv croco .. || exit 1
cd ..
rm -f obs.*.dat
$mpirun_cmd ./croco croco.basin-obs.in
cp basin_his.nc obs.nc
#
# 2. second run with obs.dat file
sed -i 's/undef[\t ]*TAPENADE/define TAPENADE/g' cppdefs.h
sed -i 's/undef[\t ]*AMPI/define AMPI/g' cppdefs.h

#sed -i 's/undef[\t ]*BATHY_MAY_BE_MODIFIED/define BATHY_MAY_BE_MODIFIED/' cppdefs.h
#sed -i 's/undef[\t ]*PENALIZATION/define PENALIZATION/' cppdefs.h
#sed -i 's/undef[\t ]*MPI/define MPI/' cppdefs.h
../OCEAN/jobcomp
cd Compile
make croco_adj && mv croco_adj .. || exit 1
#make croco_adj_dbg1 && mv croco_adj_dbg1 .. || exit 1
#make croco_adj_dbg2 && mv croco_adj_dbg2 .. || exit 1
cd ..

#./croco_adc croco.internal-friction-obs.in
echo "in directory `pwd`"
#./croco_tgt croco.internal-friction-obs.in
$mpirun_cmd ./croco_adj croco.basin-obs.in
#mpirun -np 1 ./croco_adj_dbg1 croco.internal-friction-obs.in &
#mpirun -np 1 ./croco_adj_dbg2 croco.internal-friction-obs.in
