#!/bin/bash
#OAR --project moise-modeling
#OAR -l /nodes=1/cpu=1/core=4,walltime=5:00:00

################################################################################
case $1 in
  --env-ok)
    shift;;
  *)
    # guix environment setup
    [ -f /applis/site/guix.sh ] && . /applis/site/guix.sh
    export PATH="$HOME/.guix-profile/bin${PATH:+:}$PATH"
    export PATH="$HOME/.config/guix/current/bin:${PATH}"
    pwd=`pwd`
    rm -f $pwd/.croco-guix-profile
    packages="gcc-toolchain gfortran-toolchain make \
        netcdf netcdf-fortran \                
        mpich openssh adjoinable-mpi \         
        openblas lapack \            
        openjdk coreutils binutils sed grep bash which"
    guix_cmd="guix time-machine --url=https://gitlab.inria.fr/bremond/guix.git --branch=check-master-mpich --"
    exec $guix_cmd environment --root=$pwd/.croco-guix-profile --preserve 'OAR*' --pure --ad-hoc $packages -- $0 --env-ok $@
    ;;
esac
################################################################################

set -x
set -e

if [ -f "$OAR_NODE_FILE" ]; then
  nbcores=`cat $OAR_NODE_FILE|wc -l`
  mpirun_cmd="mpirun -n $nbcores -launcher ssh -launcher-exec /usr/bin/oarsh --machinefile $OAR_NODE_FILE"
else
  nbcores=4
  mpirun_cmd="mpirun -n $nbcores"
fi

mkdir -p RunC
cd RunC

# 1. first run with ANA_INITIAL to build obs.nc file
ln -sf ../AD/croco.in.AD-DL-Z0B-CTRL-OBS.in
rm -f cppdefs.h # std cppdefs.h from OCEAN must be used
../OCEAN/jobcomp
./croco croco.in.AD-DL-Z0B-CTRL-OBS.in
cp ftides_his.nc obs.nc

# 2. second run with restart and control with obs.nc file
ln -sf ../AD/croco.in.AD-DL-Z0B-CTRL.in
cp ../OCEAN/cppdefs.h .
sed -i 's/define ANA_INITIAL/undef ANA_INITIAL/' cppdefs.h
../OCEAN/jobcomp
$mpirun_cmd ./croco_adc croco-ad-ftides.in
