#!/bin/sh
######################################################
#  PROJECT  : IO Catcher                             #
#  LICENSE  : Apache 2.0                             #
#  COPYRIGHT: 2020-2022 Bull SAS All rights reserved #
######################################################

######################################################
#set project name
cfg_set_projet "CROCO"

######################################################
#this is an MPI app, we directly use the mpi wrappers
CFG_EXTRA_CC='mpicc'
CFG_EXTRA_FORT='mpifort'

######################################################
#coverage
cfg_add_enable_option --name='psyclone-openacc' \
                      --on='-DENABLE_PSYCLONE_OPENACC=${ON} -DCMAKE_Fortran_COMPILER=nvfortran' \
                      --doc='Enable coverage report'

#psyclone venv
cfg_add_with_option   --name='psyclone' \
                      --doc='Define venv directory to get access to psyclone & poseidon' \
                      --var='PSYCLONE_PREFIX'\
                      --on='-DENABLE_PSYCLONE_OPENACC=${ON} -DCMAKE_Fortran_COMPILER=nvfortran'

#select the case to run
cfg_add_with_option   --name='case' \
                      --doc='Define the CASE to compiler and run (look in OCEAN/config.h.in)' \
                      --var='WITH_CASE'

######################################################
#If we want to document extra options
#CFG_CUSTOM_HELP="My custom options:"

######################################################
# here we can parse our own options if we want
# Vars available are :
#  - $arg : full argument (eg. --with-gcc=gcc)
#  - $val : value after first '=', egg 'gcc'
#  - $ON $OFF, $ENABLE, $DISABLE, $WIDTH, $WITHOUT
#cfg_parse_custom_opts()
#{
#	return 1
#}

######################################################
#pre check to ease error messages
#All cmake vars are loaded in memory as OPT_* (OPT_CMAKE_C_FLAGS)
#cfg_custom_pre_check()
#{
#	return 1
#}
