# Makefile for MS3DVAR Medium Resolution (MR) variant
#
# This is a simple variant-specific Makefile that includes
# the common build rules from ../Makefile.inc

# Variant-specific settings
VARIANT_NAME = MR
SBIN = msmr

# Include common build rules
include ../Makefile.inc
