#!/bin/bash

#- 
# Variables automatically set by  ci in .gitlab-ci.yml
# DO NOT overwrite
#  CVTKHOME: "$CI_PROJECT_DIR/CVTK/test_repro/CVTK_DEBUG_FAST_src"
#  DATADIR: "$CI_PROJECT_DIR/.datadir"
#  CVTKWORK: "$CI_PROJECT_DIR/.datawork"
#  CROCO_CI_MPIRUN: "mpirun.mpich"
#--

#==================================================================
# Interactive and CI
CI_FC=gfortran
CI_MPIF90=mpif90
CI_CROCO_PWD=$(pwd)
SOURCE_CROCO="$CI_PROJECT_DIR/OCEAN"
#echo "SOURCE_CROCO is: ${SOURCE_CROCO}"
TESTROOTDIR=${CVTKWORK}

# Here define the direcory with the input files
# => for BENGULEA_VHR
export DATAREG="$CI_PROJECT_DIR/../../../../VHR_CROCO_FILES_BCK"
nest_position_reg="79 137 37 117 3 3 3 3"
# => for VORTEX if needed
export DATAVOR=""
nest_position_vort=""
# => for ANA if needed
export DATAANA=""
#==================================================================
#-
FANCY_OUTPUT=1
if [ ${FANCY_OUTPUT} -eq 1 ] ;then
    #  FMT_BLUEBLD=$(tput setaf 14 ; tput bold)
    FMT_BLUEBLD=$(tput setaf 14 )
    FMT_ORD='\033[0m'
    #FMT_ORD=$(tput sgr0)
    FMT_GREEN=$(tput setaf 2)
    FMT_ORANGE=$(tput setaf 172)
    FMT_RED=$(tput setaf 1)
    FMT_RED2=$(tput setaf 9)
    FMT_GREENBLD=$(tput setaf 2 ; tput bold )
    FMT_REDBLD=$(tput setaf 1 ; tput bold )
    FMT_RVERT=$(  tput setab 7 ; tput bold )
else
    FMT_BLUEBLD=""
    FMT_ORD=""
    FMT_GREEN=""
    FMT_ORANGE=""
    FMT_RED=""
    FMT_RED2=""
    FMT_GREENBLD=""
    FMT_REDBLD=""
    FMT_RVERT=""
fi


COMPUTER=LINUX

if [ "${COMPUTER}"=="LINUX" ]; then
    # Computer dependant function to submit jobs
    SUBMIT_DIR=$CI_CROCO_PWD
    MPIRUN=$CROCO_CI_MPIRUN
    
    function Fqsub_serial() {
	./comp_run_serial.bash
    }
    function Fqsub_openmp() {
	./comp_run_openmp.bash
    }
    function Fqsub_mpi() {
	./comp_run_mpi.bash
    }
    function Fextract_results() {
	FLAG_MPI=$1
	FLAG_OPENMP=$2
	if [[ ${FLAG_MPI} -eq 1 &&  ${FLAG_OPENMP} -eq 1 ]]; then 
	    ./extract_results_croco.bash
	elif [ ${FLAG_OPENMP} -eq  1 ]; then 
	    ./extract_results_croco.bash
	elif [ ${FLAG_MPI} -eq 1 ]; then 
	    ./extract_results_croco.bash
	else
	    sed -e '3c ?' ${TEST_NAME}_steps > tmp.txt 
	    \mv tmp.txt ${TEST_NAME}_steps
	fi
    }
fi
