# Makefile for MS3DVAR Multi-Scale (MS) variant
#
# This is a simple variant-specific Makefile that includes
# the common build rules from ../Makefile.inc

# Variant-specific settings
VARIANT_NAME = MS
SBIN = msms

# Include common build rules
include ../Makefile.inc
