!     -*- fortran -*-
      call ADTOOL_AMPI_TURN(buf_rev4,buf_rev4b)
      call ADTOOL_AMPI_TURN(buf_rev3,buf_rev3b)
      call ADTOOL_AMPI_TURN(buf_rev2,buf_rev2b)
      call ADTOOL_AMPI_TURN(buf_rev1,buf_rev1b)
      call ADTOOL_AMPI_TURN(ibuf_revn,ibuf_revnb)
      call ADTOOL_AMPI_TURN(ibuf_revs,ibuf_revsb)
      call ADTOOL_AMPI_TURN(jbuf_reve,jbuf_reveb)
      call ADTOOL_AMPI_TURN(jbuf_revw,jbuf_revwb)
      call ADTOOL_AMPI_TURN(buf_snd4,buf_snd4b)
      call ADTOOL_AMPI_TURN(buf_snd3,buf_snd3b)
      call ADTOOL_AMPI_TURN(buf_snd2,buf_snd2b)
      call ADTOOL_AMPI_TURN(buf_snd1,buf_snd1b)
      call ADTOOL_AMPI_TURN(ibuf_snds,ibuf_sndsb)
      call ADTOOL_AMPI_TURN(ibuf_sndn,ibuf_sndnb)
      call ADTOOL_AMPI_TURN(jbuf_sndw,jbuf_sndwb)
      call ADTOOL_AMPI_TURN(jbuf_snde,jbuf_sndeb)
