#!/bin/bash

LIST_KEY0='REGIONAL MPI OPENMP'
# => Keys that will put to undef at the begining of the rvtk scripts

TEST_NAME='IGW'
CONFIG_NAME='IGW'
LIST_KEY_PHYS='IGW'
LIST_KEY_PAR='OPENMP MPI' 
FLAG_OPENMP=1 ; FLAG_MPI=1
LIST_KEY_NEST=''
KEY_DEBUG='RVTK_DEBUG'
CROCOIN=''
